apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: todo-app
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluMTIzQG1vbmdvLTAubW9uZ28udG9kby1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvdG9kb3M/YXV0aFNvdXJjZT1hZG1pbg==
  CORS_ORIGIN: aHR0cHM6Ly90b2RvLmlpdGMtY291cnNlLmNvbQ==
