# NOTE: Replace with real secret values before production.
# MONGO_URI base64: mongodb://admin:admin123@mongo-0.mongo.todo-app.svc.cluster.local:27017/todos?authSource=admin
# CORS_ORIGIN base64: https://todo.iitc-course.com
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: backend-secret
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-app
type: Opaque
data:
  # echo -n 'mongodb://admin:admin123@mongo-0.mongo.todo-app.svc.cluster.local:27017/todos?authSource=admin' | base64
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluMTIzQG1vbmdvLTAubW9uZ28udG9kby1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvdG9kb3M/YXV0aFNvdXJjZT1hZG1pbg==
  # echo -n 'https://todo.iitc-course.com' | base64
  CORS_ORIGIN: aHR0cHM6Ly90b2RvLmlpdGMtY291cnNlLmNvbQ==
